# Generated by Django 6.1.1 on 2026-09-07 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('offer_id', models.CharField(blank=True, max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ScanSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(max_length=32)),
                ('offer_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FlightOfferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=8)),
                ('dest', models.CharField(max_length=8)),
                ('depart_date', models.DateField()),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=8)),
                ('stops', models.PositiveSmallIntegerField()),
                ('duration_min', models.PositiveIntegerField()),
                ('airlines', models.CharField(max_length=64)),
                ('score', models.FloatField(default=0)),
                ('payload', models.JSONField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='flights.scansnapshot')),
            ],
            options={
                'ordering': ['-score', 'price'],
                'indexes': [models.Index(fields=['origin', 'dest', 'depart_date', 'snapshot'], name='flights_fli_origin_0c7258_idx')],
            },
        ),
    ]
